### ISSUE TITLE
Tiene que poder llevarme al perfil del usuario que se ha escrito en el input correspondiente

### ISSUE THREAD

**Issue by StefAranzazu** [Efornies/conditional-profile-card#2]
Hecho!

_Originally posted by @Efornies in https://github.com/Efornies/conditional-profile-card/issues/1#issuecomment-1077930270_

**Comment by Efornies** [comment]
Aaah... madre mía que disparate he hecho.. ok!!! sorry

**Comment by Efornies** [comment]
HECHO!
